site_name: Dokumentasi
pages:
  - 'Biofisika':
    - 'Bagian 1. Berkenalan': 'biofisika/1-berkenalan.md'
    - 'Bagian 2. Aturan': 'biofisika/2-aturan.md'
  - 'Elektromagnetika':
    - 'Bagian 1. Induktor': 'elektromagnetika/1-induktor.md'
theme: 'readthedocs'
repo_name: 'GitHub'
repo_url: 'https://github.com/rengganisridwan/dokumentasi-tf'

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math